[WIP][LIGHTSPD-34] fixed a bug where overnight sync was syncing with incorrect values
vtex-apps/lightspeed pull request #34
Opened 2022-04-01 19:38 UTC by whc105

2022-04-04 17:32 UTC, arturmagalhaesjr requested changes

2022-04-04 17:32 UTC, arturmagalhaesjr commented on node/utils/SyncCatalog.ts
> +
There is a logger.info that is logging the updated items inventory, however, there are many promises which are no catch or try statements. I'd catch them and put the logger.error at least.

2022-04-04 17:32 UTC, arturmagalhaesjr commented on node/utils/SyncCatalog.ts
> +    skuQuantityRemap[item.sku] = item.newQuantity
``` suggestion
    if (item?.sku) {
       skuQuantityRemap[item.sku] = item.newQuantity
    }
```

2022-04-04 17:49 UTC, whc105 commented on node/utils/SyncCatalog.ts
> +    skuQuantityRemap[item.sku] = item.newQuantity
I don't think we need to check the SKU. The sku field should always be present in the response
https://developers.vtex.com/vtex-rest-api/reference/inventorybysku

2022-04-04 18:10 UTC, whc105 commented on node/utils/SyncCatalog.ts
> +
Resolved in new commit

2022-04-05 20:22 UTC, wender approved these changes

2022-04-05 20:24 UTC, merged