[LIGHTSpD-37] add shipping
vtex-apps/lightspeed pull request #36
Opened 2022-04-19 20:26 UTC by aurorahey

**What problem is this solving?**

Added shipping information in CreateSaleLine step

**How should this be manually tested?**

[https://aurora--benscycle.myvtex.com/admin/lightspeed](url)
Retry an order in the workspace and go to the order detail and you should see the `shipPrice` and update amout

2022-04-19 21:06 UTC, whc105 requested changes
Please add it to miscellaneous items
For example: This order's saleLine
https://aurora--benscycle.myvtex.com/lightspeed/_v/0/check/BC541895-01

2022-04-20 00:37 UTC, arturmagalhaesjr requested changes

2022-04-20 00:37 UTC, arturmagalhaesjr commented on node/utils/Queue.ts
> +
```suggestion
   if (shipping.length > 0) {
      shippingPrice = shipping[0].value
   }
```

2022-04-20 18:53 UTC, arturmagalhaesjr approved these changes
LGTM

2022-04-27 14:41 UTC, whc105 approved these changes

2022-04-27 14:45 UTC, merged