[LIGHTSPD-45] App Review
vtex-apps/lightspeed pull request #47
Opened 2022-07-26 19:51 UTC by aurorahey

**What problem is this solving?**

- Added new features details to the README
- Added GraphQL directive to check mutations permission
- Fixed code smells and bugs from the sonarcloud

**How should this be manually tested?**
[workspace to test](https://aurora--redoxx.myvtex.com/admin/lightspeed)

2022-07-27 15:46 UTC, whc105 requested changes

2022-07-27 15:46 UTC, whc105 commented on react/LightSpeedConfig.tsx
> +    if (deleteId !== null) {
This can be combined

2022-07-27 15:46 UTC, whc105 commented on react/components/syncManual.tsx
> +      if (index % 100 === 0) {
Shouldn't we have `inputArr.length % 40 === 0` since thats the amount of items being sent over

2022-07-27 15:46 UTC, whc105 commented on react/components/syncManual.tsx
> +        await client.mutate(mutation)
Instead of doing await on every iteration, we can have an array of promises and just do promise all at the end

2022-07-27 15:46 UTC, whc105 commented on react/components/syncManual.tsx
> +          newQuantity = parseInt(shop.qoh, 10)
Maybe we can add a `break` here

2022-07-27 15:46 UTC, whc105 commented on react/components/syncManual.tsx
> +    if (numItems > 100) {
We can get rid of this check.

2022-07-27 20:49 UTC, whc105 requested changes

2022-07-27 20:49 UTC, whc105 commented on react/components/syncManual.tsx
> +        promises.push(mutation)
Why not just do
`promises.push(client.mutate(mutation))`

2022-07-27 20:50 UTC, whc105 commented on react/components/syncManual.tsx
> +      if (index % 100 === 0) {
InputArr isn't checked here

2022-07-28 15:28 UTC, aurorahey commented on react/components/syncManual.tsx
> +      if (index % 100 === 0) {
The index value is not from the itemsArr, it is generated when fetching the data. And this index value is necessary to get the price in `const price = parseFloat(item.Prices.ItemPrice[0].amount)` . 
I think using the index here would be better

2022-07-28 20:43 UTC, whc105 approved these changes
LGTM

2022-08-01 13:33 UTC, merged